# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residents.Property')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_external_id', models.CharField(max_length=32)),
                ('resident_external_id', models.CharField(max_length=32)),
                ('date', models.DateField(db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='residentlog',
            unique_together=set([('property_external_id', 'resident_external_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='resident',
            unique_together=set([('property', 'external_id')]),
        ),
    ]
