# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentlog',
            name='email',
            field=models.EmailField(default='test@adf.com', max_length=254),
            preserve_default=False,
        ),
    ]
